# Generated by Django 2.2.12 on 2021-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Type_job',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
