# Generated by Django 2.2.12 on 2021-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_type_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Type_job',
            field=models.CharField(choices=[('full time', 'Full Time'), ('Part time', 'Part Time')], max_length=15),
        ),
    ]
