# Generated by Django 2.2.12 on 2021-08-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210827_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descrption',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
