# Generated by Django 2.2.12 on 2021-08-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('webside', models.URLField()),
                ('cv', models.FileField(upload_to='Apply/')),
                ('cover_letter', models.TextField(max_length=500)),
            ],
        ),
    ]
