# Generated by Django 2.2.12 on 2021-08-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_apply_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
    ]
