# Generated by Django 2.2.12 on 2021-08-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_apply_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='job_link',
        ),
    ]
