# Generated by Django 2.2.12 on 2021-09-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_apply_job_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='job_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
        ),
    ]
