# Generated by Django 2.2.12 on 2021-09-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_remove_apply_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='job_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
            preserve_default=False,
        ),
    ]
